# Generated by Django 3.2 on 2022-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nutritional_value',
            field=models.TextField(blank=True, verbose_name='Пищевая ценность продукта на 100 г'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='масса/вес (гр)'),
        ),
    ]
