# Generated by Django 3.2 on 2022-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220504_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='масса/вес (гр)'),
        ),
    ]
